#!/usr/bin/env bash

if [[ "$#" -ne 1 ]]; then
  echo "Usage: manage_my_process {start|stop|restart}"
  exit 1
fi

case "$1" in
  start)
    ./manage_my_process &
    echo "$!" > /var/run/my_process.pid
    echo "manage_my_process started"
    ;;
  stop)
    if [[ -f /var/run/my_process.pid ]]; then
      kill "$(cat /var/run/my_process.pid)" && rm /var/run/my_process.pid
      echo "manage_my_process stopped"
    else
      echo "No PID file found. Is manage_my_process running?"
    fi
    ;;
  restart)
    if [[ -f /var/run/my_process.pid ]]; then
      kill "$(cat /var/run/my_process.pid)" && rm /var/run/my_process.pid
    fi
    ./manage_my_process &
    echo "$!" > /var/run/my_process.pid
    echo "manage_my_process restarted"
    ;;
  *)
    echo "Usage: manage_my_process {start|stop|restart}"
    exit 1
    ;;
esac

